=== DuongXuanBinh/Baitap/JSON/out/production/JSON/Lab2/Book.dtd
<!ELEMENT p (#PCDATA)>
<!ELEMENT BOOK (OPENER,SUBTITLE?,INTRODUCTION?,(SECTION|PART)+)>
<!ELEMENT OPENER (TITLE_TEXT)*>
<!ELEMENT TITLE_TEXT (#PCDATA)>
<!ELEMENT SUBTITLE (#PCDATA)>
<!ELEMENT INTRODUCTION (HEADER,p+)+>
<!ELEMENT PART (HEADER,CHAPTER+)>
<!ELEMENT SECTION (HEADER,p+)>
<!ELEMENT HEADER (#PCDATA)>
<!ELEMENT CHAPTER (CHAPTER_NUMBER,CHAPTER_TEXT)>
<!ELEMENT CHAPTER_NUMBER (#PCDATA)>
<!ELEMENT CHAPTER_TEXT (p)+>
<!ATTLIST PART ID CDATA #REQUIRED>
<!ENTITY GLAD "Glad you want to hear about me.">

=== DuongXuanBinh/Baitap/JSON/src/Lab2/Book.xml
<?xml version="1.0"?>
<!DOCTYPE BOOK SYSTEM "Book.dtd">
<BOOK>
    <OPENER>
        <TITLE_TEXT>
            All about me
        </TITLE_TEXT>
    </OPENER>
    <PART ID="P01">
        <HEADER>Welcome To My Book</HEADER>
        <CHAPTER>
            <CHAPTER_NUMBER>CHAPTER 1</CHAPTER_NUMBER>
            <CHAPTER_TEXT>
                <p>&GLAD;</p>
                <p>There's so much to stay!</p>
                <p>where should we start?</p>
                <p>How about more about me?</p>
            </CHAPTER_TEXT>
        </CHAPTER>
    </PART>
</BOOK>
